### PR TITLE
Migrate to integration instead of sandbox urls and update NuGet spec files

### PR DESCRIPTION
**Pull request by wooddani**

### CODE REVIEW

**Comment by weitzhandler** [comment]
Yep. Compelling.
Thank you!

**Comment by misbach** [comment]
@wooddani Is there a reason why we never accepted this request? Was it just an oversight on my part?

**Comment by weitzhandler** [comment]
This is how I'm currently using the SDK:

    var uri = new Uri("https://integration.familysearch.org/platform/collections/tree");
    var tree = new FamilySearchFamilyTree(uri);
    var state = tree.AuthenticateViaOAuth2Password(Username, Password, ClientId);

**Comment by wooddani** [comment]
No reason that I know of. I thought this had been accepted and odd that it is a new pull request. If I need to push a new NuGet out I can. I will look at my NuGet push directly and see if it went up.

**Comment by wooddani** [comment]
It may have just shown up because of https://github.com/weitzhandler 's comment

**Comment by misbach** [comment]
Weird! It looks like we never merged this. Check out this line, it still shows "sandbox" instead of "integration" which this pull request has.
https://github.com/FamilySearch/gedcomx-csharp/blob/master/FamilySearch.Api/EnvironmentEnum.cs#L8

I'll merge it, and you can push out the nuget packages.

**Pull request merged**
