### PR TITLE
Migrated GedcomxDate methods to properties

### PR DESCRIPTION
**Pull request by weitzhandler**
Properties are easier to bind to and should be preferred over methods in .NET apps.

### CODE REVIEW

**Comment by misbach** [comment]
@wooddani What do you think of this PR?

**Comment by weitzhandler** [comment]
This is a breaking change, since all usages will have to be changed from `IsApproximate()` to `IsApproximate`, and from `ToFormatString` to `FormalString`.
I committed this but there are plenty occasions in the API that use methods where a Microsoft dev would have used properties.

Bare in mind that C# and .NET, especially now with Xamarin starting to become such a buzz and the glory starts to shine back on XAML, properties should be preferred over methods - when it makes sense.

**Comment by wooddani** [comment]
Looks good and very appropriate. That code is well over 3 years old and methodology has changed.

**Comment by weitzhandler** [comment]
Really this was a test, I have plenty more changes to make to .NETify the SDK which feels JAVAish.

**Comment by weitzhandler** [comment]
WOW thanks fellas for adding me as a contributor. I unfortunately had to take another project now that will keep me busy for a month or some more. But genealogy is high on my radar. I hope to come back to my hobby gene project real soon!

**Pull request merged**
